// <auto-generated />
using System;
using HCSearch.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HCSearch.Migrations
{
    [DbContext(typeof(PersonContext))]
    [Migration("20190614182833_HCSearch.Models.PersonContext")]
    partial class HCSearchModelsPersonContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HCSearch.Models.PersonInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressCity")
                        .HasMaxLength(255);

                    b.Property<string>("AddressCountry")
                        .HasMaxLength(255);

                    b.Property<string>("AddressState")
                        .HasMaxLength(255);

                    b.Property<string>("AddressStreet")
                        .HasMaxLength(255);

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Interests")
                        .HasMaxLength(4000);

                    b.Property<byte[]>("Picture")
                        .HasColumnType("varbinary(Max)");

                    b.HasKey("Id");

                    b.ToTable("PersonInfos");
                });

            modelBuilder.Entity("HCSearch.Models.PersonName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameFirst")
                        .HasMaxLength(255);

                    b.Property<string>("NameLast")
                        .HasMaxLength(255);

                    b.Property<int>("PersonInfoFK");

                    b.HasKey("Id");

                    b.ToTable("PersonNames");
                });
#pragma warning restore 612, 618
        }
    }
}
